#include "PlayFabLocalizationModelDecoder.h"

struct FLocalizationGetLanguageListResponse UPlayFabLocalizationModelDecoder::STATIC_decodeGetLanguageListResponseResponse(class UPlayFabJsonObject* response) {
}
