#include "PlayFabServerModelDecoder.h"

struct FServerWriteEventResponse UPlayFabServerModelDecoder::STATIC_decodeWriteEventResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdateUserDataResult UPlayFabServerModelDecoder::STATIC_decodeUpdateUserDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdateSharedGroupDataResult UPlayFabServerModelDecoder::STATIC_decodeUpdateSharedGroupDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdatePlayerStatisticsResult UPlayFabServerModelDecoder::STATIC_decodeUpdatePlayerStatisticsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdateCharacterStatisticsResult UPlayFabServerModelDecoder::STATIC_decodeUpdateCharacterStatisticsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdateCharacterDataResult UPlayFabServerModelDecoder::STATIC_decodeUpdateCharacterDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUpdateBansResult UPlayFabServerModelDecoder::STATIC_decodeUpdateBansResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUnlockContainerItemResult UPlayFabServerModelDecoder::STATIC_decodeUnlockContainerItemResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUnlinkXboxAccountResult UPlayFabServerModelDecoder::STATIC_decodeUnlinkXboxAccountResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerUnlinkServerCustomIdResult UPlayFabServerModelDecoder::STATIC_decodeUnlinkServerCustomIdResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetTitleDataResult UPlayFabServerModelDecoder::STATIC_decodeSetTitleDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetPublisherDataResult UPlayFabServerModelDecoder::STATIC_decodeSetPublisherDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetPlayerSecretResult UPlayFabServerModelDecoder::STATIC_decodeSetPlayerSecretResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetGameServerInstanceTagsResult UPlayFabServerModelDecoder::STATIC_decodeSetGameServerInstanceTagsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetGameServerInstanceStateResult UPlayFabServerModelDecoder::STATIC_decodeSetGameServerInstanceStateResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSetGameServerInstanceDataResult UPlayFabServerModelDecoder::STATIC_decodeSetGameServerInstanceDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerServerLoginResult UPlayFabServerModelDecoder::STATIC_decodeServerLoginResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSendPushNotificationResult UPlayFabServerModelDecoder::STATIC_decodeSendPushNotificationResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSendEmailFromTemplateResult UPlayFabServerModelDecoder::STATIC_decodeSendEmailFromTemplateResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSendCustomAccountRecoveryEmailResult UPlayFabServerModelDecoder::STATIC_decodeSendCustomAccountRecoveryEmailResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerSavePushNotificationTemplateResult UPlayFabServerModelDecoder::STATIC_decodeSavePushNotificationTemplateResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRevokeInventoryResult UPlayFabServerModelDecoder::STATIC_decodeRevokeInventoryResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRevokeInventoryItemsResult UPlayFabServerModelDecoder::STATIC_decodeRevokeInventoryItemsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRevokeBansResult UPlayFabServerModelDecoder::STATIC_decodeRevokeBansResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRevokeAllBansForUserResult UPlayFabServerModelDecoder::STATIC_decodeRevokeAllBansForUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerReportPlayerServerResult UPlayFabServerModelDecoder::STATIC_decodeReportPlayerServerResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRemoveSharedGroupMembersResult UPlayFabServerModelDecoder::STATIC_decodeRemoveSharedGroupMembersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRemovePlayerTagResult UPlayFabServerModelDecoder::STATIC_decodeRemovePlayerTagResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRegisterGameResponse UPlayFabServerModelDecoder::STATIC_decodeRegisterGameResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRefreshGameServerInstanceHeartbeatResult UPlayFabServerModelDecoder::STATIC_decodeRefreshGameServerInstanceHeartbeatResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRedeemMatchmakerTicketResult UPlayFabServerModelDecoder::STATIC_decodeRedeemMatchmakerTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerRedeemCouponResult UPlayFabServerModelDecoder::STATIC_decodeRedeemCouponResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerNotifyMatchmakerPlayerLeftResult UPlayFabServerModelDecoder::STATIC_decodeNotifyMatchmakerPlayerLeftResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerMoveItemToUserFromCharacterResult UPlayFabServerModelDecoder::STATIC_decodeMoveItemToUserFromCharacterResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerMoveItemToCharacterFromUserResult UPlayFabServerModelDecoder::STATIC_decodeMoveItemToCharacterFromUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerMoveItemToCharacterFromCharacterResult UPlayFabServerModelDecoder::STATIC_decodeMoveItemToCharacterFromCharacterResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerModifyUserVirtualCurrencyResult UPlayFabServerModelDecoder::STATIC_decodeModifyUserVirtualCurrencyResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerModifyItemUsesResult UPlayFabServerModelDecoder::STATIC_decodeModifyItemUsesResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerModifyCharacterVirtualCurrencyResult UPlayFabServerModelDecoder::STATIC_decodeModifyCharacterVirtualCurrencyResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerListUsersCharactersResult UPlayFabServerModelDecoder::STATIC_decodeListUsersCharactersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerLinkXboxAccountResult UPlayFabServerModelDecoder::STATIC_decodeLinkXboxAccountResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerLinkServerCustomIdResult UPlayFabServerModelDecoder::STATIC_decodeLinkServerCustomIdResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGrantItemsToUsersResult UPlayFabServerModelDecoder::STATIC_decodeGrantItemsToUsersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGrantItemsToUserResult UPlayFabServerModelDecoder::STATIC_decodeGrantItemsToUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGrantItemsToCharacterResult UPlayFabServerModelDecoder::STATIC_decodeGrantItemsToCharacterResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGrantCharacterToUserResult UPlayFabServerModelDecoder::STATIC_decodeGrantCharacterToUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetUserInventoryResult UPlayFabServerModelDecoder::STATIC_decodeGetUserInventoryResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetUserDataResult UPlayFabServerModelDecoder::STATIC_decodeGetUserDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetUserBansResult UPlayFabServerModelDecoder::STATIC_decodeGetUserBansResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetUserAccountInfoResult UPlayFabServerModelDecoder::STATIC_decodeGetUserAccountInfoResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetTitleNewsResult UPlayFabServerModelDecoder::STATIC_decodeGetTitleNewsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetTitleDataResult UPlayFabServerModelDecoder::STATIC_decodeGetTitleDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetTimeResult UPlayFabServerModelDecoder::STATIC_decodeGetTimeResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetSharedGroupDataResult UPlayFabServerModelDecoder::STATIC_decodeGetSharedGroupDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetServerCustomIDsFromPlayFabIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetServerCustomIDsFromPlayFabIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetRandomResultTablesResult UPlayFabServerModelDecoder::STATIC_decodeGetRandomResultTablesResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPublisherDataResult UPlayFabServerModelDecoder::STATIC_decodeGetPublisherDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromXboxLiveIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromXboxLiveIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromSteamIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromSteamIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromPSNAccountIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromPSNAccountIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromNintendoSwitchDeviceIdsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromNintendoSwitchDeviceIdsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromGenericIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromGenericIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromFacebookInstantGamesIdsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromFacebookInstantGamesIdsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayFabIDsFromFacebookIDsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayFabIDsFromFacebookIDsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerTagsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerTagsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerStatisticVersionsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerStatisticVersionsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerStatisticsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerStatisticsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayersInSegmentResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayersInSegmentResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerSegmentsResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerSegmentsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerProfileResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerProfileResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetPlayerCombinedInfoResult UPlayFabServerModelDecoder::STATIC_decodeGetPlayerCombinedInfoResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetLeaderboardResult UPlayFabServerModelDecoder::STATIC_decodeGetLeaderboardResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetLeaderboardForUsersCharactersResult UPlayFabServerModelDecoder::STATIC_decodeGetLeaderboardForUsersCharactersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetLeaderboardAroundUserResult UPlayFabServerModelDecoder::STATIC_decodeGetLeaderboardAroundUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetLeaderboardAroundCharacterResult UPlayFabServerModelDecoder::STATIC_decodeGetLeaderboardAroundCharacterResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetFriendsListResult UPlayFabServerModelDecoder::STATIC_decodeGetFriendsListResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetContentDownloadUrlResult UPlayFabServerModelDecoder::STATIC_decodeGetContentDownloadUrlResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetCharacterStatisticsResult UPlayFabServerModelDecoder::STATIC_decodeGetCharacterStatisticsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetCharacterLeaderboardResult UPlayFabServerModelDecoder::STATIC_decodeGetCharacterLeaderboardResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetCharacterInventoryResult UPlayFabServerModelDecoder::STATIC_decodeGetCharacterInventoryResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetCharacterDataResult UPlayFabServerModelDecoder::STATIC_decodeGetCharacterDataResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetCatalogItemsResult UPlayFabServerModelDecoder::STATIC_decodeGetCatalogItemsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerGetAllSegmentsResult UPlayFabServerModelDecoder::STATIC_decodeGetAllSegmentsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerExecuteCloudScriptResult UPlayFabServerModelDecoder::STATIC_decodeExecuteCloudScriptResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerEvaluateRandomResultTableResult UPlayFabServerModelDecoder::STATIC_decodeEvaluateRandomResultTableResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerEmptyResult UPlayFabServerModelDecoder::STATIC_decodeEmptyResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerEmptyResponse UPlayFabServerModelDecoder::STATIC_decodeEmptyResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FServerDeregisterGameResponse UPlayFabServerModelDecoder::STATIC_decodeDeregisterGameResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FServerDeletePushNotificationTemplateResult UPlayFabServerModelDecoder::STATIC_decodeDeletePushNotificationTemplateResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerDeletePlayerResult UPlayFabServerModelDecoder::STATIC_decodeDeletePlayerResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerDeleteCharacterFromUserResult UPlayFabServerModelDecoder::STATIC_decodeDeleteCharacterFromUserResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerCreateSharedGroupResult UPlayFabServerModelDecoder::STATIC_decodeCreateSharedGroupResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerConsumeItemResult UPlayFabServerModelDecoder::STATIC_decodeConsumeItemResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerBanUsersResult UPlayFabServerModelDecoder::STATIC_decodeBanUsersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerAwardSteamAchievementResult UPlayFabServerModelDecoder::STATIC_decodeAwardSteamAchievementResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerAuthenticateSessionTicketResult UPlayFabServerModelDecoder::STATIC_decodeAuthenticateSessionTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerAddSharedGroupMembersResult UPlayFabServerModelDecoder::STATIC_decodeAddSharedGroupMembersResultResponse(class UPlayFabJsonObject* response) {
}
	struct FServerAddPlayerTagResult UPlayFabServerModelDecoder::STATIC_decodeAddPlayerTagResultResponse(class UPlayFabJsonObject* response) {
}
