#include "PlayFabAuthenticationModelDecoder.h"

struct FAuthenticationGetEntityTokenResponse UPlayFabAuthenticationModelDecoder::STATIC_decodeGetEntityTokenResponseResponse(class UPlayFabJsonObject* response) {
}
