#include "PlayFabMultiplayerModelDecoder.h"

struct FMultiplayerRolloverContainerRegistryCredentialsResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeRolloverContainerRegistryCredentialsResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerRequestMultiplayerServerResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeRequestMultiplayerServerResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListVirtualMachineSummariesResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListVirtualMachineSummariesResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListQosServersResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListQosServersResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListMultiplayerServersResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListMultiplayerServersResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListMatchmakingTicketsForPlayerResult UPlayFabMultiplayerModelDecoder::STATIC_decodeListMatchmakingTicketsForPlayerResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListContainerImageTagsResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListContainerImageTagsResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListContainerImagesResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListContainerImagesResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListCertificateSummariesResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListCertificateSummariesResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListBuildSummariesResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListBuildSummariesResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerListAssetSummariesResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeListAssetSummariesResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerJoinMatchmakingTicketResult UPlayFabMultiplayerModelDecoder::STATIC_decodeJoinMatchmakingTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetTitleMultiplayerServersQuotasResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetTitleMultiplayerServersQuotasResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetTitleEnabledForMultiplayerServersStatusResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetTitleEnabledForMultiplayerServersStatusResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetRemoteLoginEndpointResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetRemoteLoginEndpointResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetQueueStatisticsResult UPlayFabMultiplayerModelDecoder::STATIC_decodeGetQueueStatisticsResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetMultiplayerServerDetailsResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetMultiplayerServerDetailsResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetMatchResult UPlayFabMultiplayerModelDecoder::STATIC_decodeGetMatchResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetMatchmakingTicketResult UPlayFabMultiplayerModelDecoder::STATIC_decodeGetMatchmakingTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetContainerRegistryCredentialsResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetContainerRegistryCredentialsResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetBuildResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetBuildResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerGetAssetUploadUrlResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeGetAssetUploadUrlResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerEnableMultiplayerServersForTitleResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeEnableMultiplayerServersForTitleResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerEmptyResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeEmptyResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCreateRemoteUserResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeCreateRemoteUserResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCreateMatchmakingTicketResult UPlayFabMultiplayerModelDecoder::STATIC_decodeCreateMatchmakingTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCreateBuildWithManagedContainerResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeCreateBuildWithManagedContainerResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCreateBuildWithCustomContainerResponse UPlayFabMultiplayerModelDecoder::STATIC_decodeCreateBuildWithCustomContainerResponseResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCancelMatchmakingTicketResult UPlayFabMultiplayerModelDecoder::STATIC_decodeCancelMatchmakingTicketResultResponse(class UPlayFabJsonObject* response) {
}
	struct FMultiplayerCancelAllMatchmakingTicketsForPlayerResult UPlayFabMultiplayerModelDecoder::STATIC_decodeCancelAllMatchmakingTicketsForPlayerResultResponse(class UPlayFabJsonObject* response) {
}
