#pragma once

#include "CoreMinimal.h"
#include "EdGraphPin_Deprecated.generated.h"

UCLASS()
class UEdGraphPin_Deprecated : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FString PinName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FString PinToolTip;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	TEnumAsByte<EEdGraphPinDirection> Direction;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FEdGraphPinType PinType;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FString DefaultValue;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FString AutogeneratedDefaultValue;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	class UObject* DefaultObject;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FText DefaultTextValue;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	TArray<class UEdGraphPin_Deprecated*> LinkedTo;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	TArray<class UEdGraphPin_Deprecated*> SubPins;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	class UEdGraphPin_Deprecated* ParentPin;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	class UEdGraphPin_Deprecated* ReferencePassThroughConnection;


};