#pragma once

#include "CoreMinimal.h"
#include "SCS_Node.generated.h"

UCLASS()
class USCS_Node : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	class UClass* ComponentClass;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	class UActorComponent* ComponentTemplate;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FBlueprintCookedComponentInstancingData CookedComponentInstancingData;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName VariableName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName AttachToName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName ParentComponentOrVariableName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName ParentComponentOwnerClassName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	bool bIsParentComponentNative;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	TArray<class USCS_Node*> ChildNodes;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	TArray<struct FBPVariableMetaDataEntry> MetaDataArray;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FGuid VariableGuid;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	bool bIsFalseRoot;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	bool bIsNative;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName NativeComponentName;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	bool bVariableNameAutoGenerated;
	UPROPERTY(Replicated, EditAnywhere, BlueprintReadWrite)
	struct FName InternalVariableName;


};